name: Python package

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Create SSH key
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
        SSH_KEY_PATH   : ${{ github.workspace }}/../private.key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > $SSH_KEY_PATH
        sudo chmod 600 $SSH_KEY_PATH
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - name: Install fabric
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install fabric3
    - name: Deploy to prod
      working-directory: ./deploy_tools
      env:
        SSH_KEY_PATH   : ${{ github.workspace }}/../private.key
        REPO_URL       : $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git
        BRANCH         : main
        SERVER_USERNAME: ${{secrets.SERVER_USERNAME}}
        SERVER_DOMAIN  : ${{secrets.SERVER_DOMAIN}}
      run: fab -i $SSH_KEY_PATH deploy:$REPO_URL,$BRANCH,$SERVER_USERNAME,host=$SERVER_USERNAME@$SERVER_DOMAIN
